apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:CR75WgluTHjhRsa6chcdP36J3nEH1cFrrWtHXNW2SFY="
  APP_DEBUG: "true"
  APP_LOG_LEVEL: "debug"
  APP_URL: "http://localhost"

  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: "3306"
  DB_DATABASE: "homestead"
  DB_USERNAME: "homestead"
  DB_PASSWORD: "secret"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_DRIVER: "sync"

  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 9000
  selector:
    app: backend
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 267270001270.dkr.ecr.us-east-1.amazonaws.com/forum-app:v1
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: laravel-config
