node {
    stage('Build and push') {
    docker.withRegistry('https://index.docker.io/v1/', 'docker-login'){    
    checkout scm

    def customImage = docker.build("jacksonlima91/forum-app:${env.BUILD_ID}")
    customImage.push()
    }
    }
    stage('Test'){
            steps{
                sh "sed -i 's/forum-app.*/forum-app:$BUILD_NUMBER/g' docker-compose.yml"
                sh "docker-compose up -d"
            }
        }
}
