node('master') {
    docker.withRegistry('https://index.docker.io/v1/', 'docker-login'){      
    stage('Build and push') { 
    checkout scm

    def customImage = docker.build("jacksonlima91/forum-app:${env.BUILD_ID}")
    customImage.push()
    }
    }
}
